### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by FPS-86** [nguyenph88/Dayz-Standalone-Default-Loadout#1]
Hi. I have a error popped up after adding your script:

---------------------------------------------
Log C:\DayZServer\ServerProfile\crash.log started at 20.12. 08:22:39

------------------------------------
SRV82045, 20.12 2018 08:22:39
Can't compile mission init script'!

$CurrentDir://mpmissions//dayzOffline.chernarusplus//scripts//SetUpPlayer.c(12): Can't find variable 'loadOutSel'

Runtime mode
CLI params: port 2502 config ServerProfile\serverDZ.cfg cfg ServerProfile\basic.cfg profiles ServerProfile dologs  adminlog  freezecheck  scriptDebug true mod @RPCFramework;@Permissions Framework;@Community Online Tools;@Trader;@BuildAnywhere;@KillFeed;@DayZ_CCCP;@PartyMe;@InventoryPlus;@SQUAD MSF-C;@Weapon Redux Pack

**Comment by FPS-86** [comment]
I apologize not to have written. Please delete my message

**Comment by nguyenph88** [comment]
sure not a problem
